### ISSUE TITLE
parallel42 / flow Pro  Lost basic wheel settings 

### ISSUE THREAD

**Issue by Gil5611** [parallel42/flow-documentation#1]
Hi I mistakenly erased basic functions on the wheel. I uninstalled P42 Flow Pro via Orbx and deleted everything that contained "flow" on my "C" drive and on my MSFS2020 SSD, but when reinstalling it, it remembered my old setting instead of the basic settings of the wheel. Please, where is the file (and its name) that keeps my preferences to delete it and start fresh? Thank you for your reply ! G

**Comment by runshotgun** [comment]
Please open a ticket at https://help.parallel42.com/
